// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20231221195137_ChangeTableNameAndPropertyAndSeedData")]
    partial class ChangeTableNameAndPropertyAndSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfReviews")
                        .HasColumnType("int");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Dublin",
                            Country = "Ireland",
                            Message = "Beautiful and friendly! Will visit again.",
                            NumberOfReviews = 234,
                            OverallRating = 10
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "St Louis",
                            Country = "United States",
                            Message = "Historic and walkable but very dirty.",
                            NumberOfReviews = 43,
                            OverallRating = 4
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Cairo",
                            Country = "Egypt",
                            Message = "Great attractions and history. Crowded and smoggy.",
                            NumberOfReviews = 435,
                            OverallRating = 7
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Puerto Vallarta",
                            Country = "Mexico",
                            Message = "Beautiful, relaxing and warm.",
                            NumberOfReviews = 128,
                            OverallRating = 9
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Shanghai",
                            Country = "China",
                            Message = "Diverse, lots of entertainment, great food.",
                            NumberOfReviews = 879,
                            OverallRating = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
